---
- hosts: all
  remote_user: root
  sudo: true
  environment:
          #    DISPLAY: ':0.0'
    PATH: "/opt/omnetpp-5.1.1/bin:/bin"
  tasks:
    - name: set hostname
      hostname:
        name: omnetdev
    
    - name: skip install assistant
      lineinfile:
        dest: /root/.config/gnome-initial-setup-done
        create: yes
        line: yes
        state: present
        
    - name: enable autologin
      lineinfile:
        dest: /etc/gdm/custom.conf
        insertafter: '^\[daemon\]'
        line: "{{ item }}"
      with_items:  
        - "AutomaticLoginEnable=true"
        - "AutomaticLogin=root"
        
    - shell:
        cmd: "{{ item }}"
      with_items:
        - "/sbin/init 3"
        - "/sbin/init 5"
        - "/bin/sleep 30"

          #    - name: restart gnome session as user
          #      systemd:
          #        name: gdm
          #        state: restarted

    - name: install yum
      shell: dnf -y install yum 

    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present

    - name: set locale 1
      command: "localectl set-locale LANG=de_AT.utf8"

    - name: set locale 2
      command: "localectl set-keymap de-nodeadkeys"

    - name: set locale 3
      command: "localectl set-x11-keymap de"

    - name: install required software
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc-c++
        - qt5-qtbase-devel
        - tk-devel
#        - nemiver
        - libpcap-devel
        - libpcap
        - openmpi-devel
        - libxml2-devel
        - flex
        - bison
        - java-1.8.0-openjdk
          #- "@X Window System"
          #- "@xfce"
        - git
        - "kernel-devel-{{ ansible_kernel }}"
        - xdg-utils
        - nano
    
    - name: remove openbox
      yum:
        name: "openbox"
        state: absent

    - name: disable selinux
      selinux:
        state: disabled

        # brauchen wir nicht mehr
        # die aktuelle box hat die guest extensions schon drin
        #    - name: build guest extensions
        #      shell: sh /vagrant/vbox/VBoxLinuxAdditions.run --nox11
        #      args:
        #        creates: /opt/VBoxGuestAdditions-5.1.28/lib/VBoxGuestAdditions/vboxvideo_drv.o
        #      register:
        #        built_guest_extensions

    - name: download omnet
      get_url:
        url: https://omnetpp.org/omnetpp/send/30-omnet-releases/2314-omnetpp-5-1-1-linux
        dest: /vagrant/omnetpp-5.1.1-src-linux.tgz
        force: no
        checksum: md5:eb7aab92f62314f4df060b5af399cddd
        headers: Referer:https://omnetpp.org/omnetpp/category/30-omnet-releases
    
    - name: extract omnet
      unarchive:
        remote_src: yes
        src: /vagrant/omnetpp-5.1.1-src-linux.tgz
        dest: /opt
        creates: /opt/omnetpp-5.1.1/configure.user
    
    - name: create symlink
      file:
        src: /opt/omnetpp-5.1.1
        dest: /opt/omnetpp
        state: link


    - name: disable osg
      lineinfile:
        path: /opt/omnetpp/configure.user
        line: "{{ item }}"
      with_items:
        - "WITH_OSGEARTH=no"
        - "WITH_OSG=no"

    - name: run configure
      command: ./configure
      args:
        chdir: /opt/omnetpp
        #  creates: /opt/omnetpp/Makefile.inc
      register: stdout_configure
      environment:
        DISPLAY: ":0.0"

    - name: run make
      command: "make {{ item }} -j 3"
      args:
        chdir: /opt/omnetpp
        creates: /opt/omnetpp-5.1.1/out/gcc-debug/src/envir/opp_run
      register: stdout_make
      with_items:
        - "base"
    
    - name: pull inet
      git:
        repo: https://github.com/inet-framework/inet.git
        dest: /opt/omnetpp/samples/inet

    - name: build inet
      command: "make {{ item }} -j 3"
      args:
        chdir: /opt/omnetpp/samples/inet
        creates: /opt/omnetpp/samples/inet/out/gcc-debug/src/libINET.so
      with_items:
        - "makefiles"
        - "all"

    - name: pull GIT projects
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      with_items:
              - repo: "https://github.com/drangur/ipen.git"
                dest: "/opt/omnetpp/samples/sdndemo"
              - repo: "https://github.com/fstolba/ofomnet.git"
                dest: "/opt/omnetpp/samples/ofomnet"


## DESKTOP STUFF GNOME SETTINGS USW



    - name: create desktop shortcut
      copy:
        src: /vagrant/opensim-ide.desktop
        dest: /root/.local/share/applications/opensim-ide.desktop
        mode: 0777

    - name: create directory
      file:
        path: /etc/dconf/db/local.d
        state: directory

    - name: set gnome settings
      copy:
        src: /vagrant/gnome-settings
        dest: /etc/dconf/db/local.d/vagrant-settings
    - lineinfile:
        create: yes
        dest: /etc/dconf/profile/user
        line: "{{ item }}"
        state: present
      with_items:
        - "user-db:user"
        - "system-db:local"

    - name: update dconf bus
      shell:
        cmd: "dconf update"

    - shell:
        cmd: "{{ item }}"
      with_items:
        - "/sbin/init 3"
        - "/sbin/init 5"
        - "/bin/sleep 30"
