ENV['VAGRANT_DEFAULT_PRODIVER'] = 'virtualbox'

# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.configure("2") do |config|
#  config.vm.box = "centos/7"
  config.vm.box = "jhcook/fedora26"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "omnet-provision.yml"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
    vb.gui = true
  end
  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true
end
